version: "3.7"

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    ports:
      - '127.0.0.1:9200:9200'
    environment:
      - discovery.type=single-node
      - node.name=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
